import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import standalone from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';
import { format } from 'prettier';

const definitions = [
  ['domain', 'domain-md.schema.json'],
  ['manifest', 'oracle-capsule.schema.json'],
  ['sourceLock', 'oracle-capsule-source-lock.schema.json'],
] as const;
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  strictRequired: false,
  strictTypes: false,
  code: { source: true },
});
addFormats.default(ajv);
const exports: Record<string, string> = {};
for (const [name, file] of definitions) {
  const schema: unknown = JSON.parse(
    readFileSync(new URL(`../spec/${file}`, import.meta.url), 'utf8'),
  );
  if (!schema || typeof schema !== 'object' || Array.isArray(schema))
    throw new Error('Invalid schema');
  ajv.addSchema(schema, name);
  exports[name] = name;
}
const result = await build({
  stdin: { contents: standalone.default(ajv, exports), resolveDir: resolve('.') },
  bundle: true,
  write: false,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  banner: {
    js: '/* eslint-disable */\n// Generated by scripts/generate-validators.ts. Do not edit.',
  },
});
const output = new URL('../packages/cli/src/compiled-validators.js', import.meta.url);
const formatted = await format(result.outputFiles[0]!.text, {
  parser: 'babel',
  singleQuote: true,
  printWidth: 100,
});
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== formatted) throw new Error('Compiled validators are stale');
} else writeFileSync(output, formatted);
